twitter bot: v1
96boards-projects/twitter-bot pull request #1
Opened 2018-10-20 16:29 UTC by ric96

Signed-off-by: Sahaj Sarup <sahaj.sarup@linaro.org>

2018-10-20 17:22 UTC, Mani-Sadhasivam requested changes
Couple of points:

1. Please always add a commit message
2. Only split out the commits if different functionalities are covered otherwise a single commit would be the best

2018-10-20 17:22 UTC, Mani-Sadhasivam commented on bot.py
>   while True:
Nested `while true` smells like the code needs to be structured better ;-)

2018-10-20 17:56 UTC, ric96 commented on bot.py
>   while True:
yea just fixed that

2018-10-20 18:02 UTC, ric96 commented
@Mani-Sadhasivam made the changes as requested

2018-10-21 03:32 UTC, Mani-Sadhasivam requested changes
Couple of nitpicks

2018-10-21 03:32 UTC, Mani-Sadhasivam commented on README.md
> +- **Test Run**
Nit: How about:

#### Test Run
 You can run it simply as
```shell
  $ python3 bot.py
```
#### Deploy
From Shell
```shell
  $ python3 bot.py &
```

2018-10-21 03:32 UTC, Mani-Sadhasivam commented on bot.py
> +import tweepy
Please add a license here!

2018-10-21 03:58 UTC, ric96 commented on bot.py
> +import tweepy
fixed

2018-10-29 13:32 UTC, Mani-Sadhasivam approved these changes
LGTM!

2018-10-29 13:32 UTC, merged